[package]
name = "jett_lsp"
description = "Language Server Protocol implementation for Jett"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jett_common.workspace = true
jett_diagnostics.workspace = true
jett_driver.workspace = true
jett_fmt.workspace = true
jett_lexer.workspace = true
jett_resolve.workspace = true
tower-lsp.workspace = true
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
