[package]
name = "jett_parser"
description = "Recursive descent parser producing a lossless CST"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jett_common.workspace = true
jett_diagnostics.workspace = true
jett_lexer.workspace = true

[dev-dependencies]
insta = "1.48.0"
