[package]
name = "jett_comptime"
description = "Compile-time interpreter for verify blocks and comptime expressions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jett_common.workspace = true
jett_diagnostics.workspace = true
jett_parser.workspace = true
jett_types.workspace = true
rand.workspace = true
subtle.workspace = true
unicode-segmentation.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Globalization"] }
