//! Identical original Source and finite script/oracle inputs for both test harnesses.
//! No record contains a runtime token, Resource key or installer authority.
#![allow(dead_code)] // Each harness consumes its own side of the shared observation oracle.
pub(crate) const SUPPORT: &str = include_str!("resource/resource_probe.jett");
#[derive(Clone, Copy, Debug)]
pub(crate) enum Script {
    Construct(i64),
    ConstructFail(i64, &'static str),
    FinalizerPanic(i64),
    Borrow(i64, i64),
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Event {
    Constructed(i64),
    ConstructionFailed(i64),
    Borrowed(i64),
    Finalized(i64),
}
#[derive(Clone, Copy, Debug)]
pub(crate) enum ReferenceOutcome {
    Clean,
    Error(&'static str),
    CleanupPanic(&'static str),
}
pub(crate) struct Case {
    pub(crate) name: &'static str,
    pub(crate) source: &'static str,
    pub(crate) script: &'static [Script],
    pub(crate) events: &'static [Event],
    pub(crate) reference: ReferenceOutcome,
    // Native status/channel literals are separate from the reference error representation.
    pub(crate) body: u32,
    pub(crate) cleanup: u32,
    pub(crate) channel: u32,
    pub(crate) ordinary_message: &'static [u8],
    pub(crate) resource_message: &'static [u8],
    pub(crate) exit: i32,
}
pub(crate) const CASES: &[Case] = &[
    Case {
        name: "connected",
        source: include_str!("resource/01_connected_entry.jett"),
        script: &[Script::Construct(1), Script::Borrow(1, 7)],
        events: &[
            Event::Constructed(1),
            Event::Borrowed(1),
            Event::Finalized(1),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "factory_fail",
        source: include_str!("resource/01_connected_entry.jett"),
        script: &[Script::ConstructFail(1, "declined")],
        events: &[Event::ConstructionFailed(1)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_actual",
        source: include_str!("resource/02_partial_actual_failure.jett"),
        script: &[Script::Construct(1)],
        events: &[Event::Constructed(1), Event::Finalized(1)],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
    Case {
        name: "implicit_drop",
        source: include_str!("resource/03_implicit_drop.jett"),
        script: &[Script::Construct(1)],
        events: &[Event::Constructed(1), Event::Finalized(1)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "finalizer_panic",
        source: include_str!("resource/03_implicit_drop.jett"),
        script: &[Script::FinalizerPanic(1)],
        events: &[Event::Constructed(1), Event::Finalized(1)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 0,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "replace_live",
        source: include_str!("resource/04_live_replace.jett"),
        script: &[
            Script::Construct(2401),
            Script::Construct(2402),
            Script::Borrow(2402, 7),
        ],
        events: &[
            Event::Constructed(2401),
            Event::Constructed(2402),
            Event::Finalized(2401),
            Event::Borrowed(2402),
            Event::Finalized(2402),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "rebind_self",
        source: include_str!("resource/05_self_rebind.jett"),
        script: &[Script::Construct(2421)],
        events: &[Event::Constructed(2421), Event::Finalized(2421)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "replace_closed",
        source: include_str!("resource/06_replace_closed.jett"),
        script: &[Script::Construct(2411), Script::Construct(2412)],
        events: &[
            Event::Constructed(2411),
            Event::Finalized(2411),
            Event::Constructed(2412),
            Event::Finalized(2412),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "rhs_domain_failure",
        source: include_str!("resource/07_rhs_domain_failure.jett"),
        script: &[
            Script::Construct(2431),
            Script::ConstructFail(2432, "rhs sentinel"),
            Script::Borrow(2431, 7),
        ],
        events: &[
            Event::Constructed(2431),
            Event::ConstructionFailed(2432),
            Event::Borrowed(2431),
            Event::Finalized(2431),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "rhs_ordinary_failure",
        source: include_str!("resource/08_rhs_ordinary_failure.jett"),
        script: &[Script::Construct(2441)],
        events: &[Event::Constructed(2441), Event::Finalized(2441)],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
    Case {
        name: "replace_old_finalizer_panic",
        source: include_str!("resource/04_live_replace.jett"),
        script: &[Script::FinalizerPanic(2401), Script::Construct(2402)],
        events: &[
            Event::Constructed(2401),
            Event::Constructed(2402),
            Event::Finalized(2401),
            Event::Finalized(2402),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "later_handle_minimal",
        source: include_str!("resource/09_later_handle_minimal.jett"),
        script: &[Script::Construct(502)],
        events: &[Event::Constructed(502), Event::Finalized(502)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_original",
        source: include_str!("resource/10_later_handle_original.jett"),
        script: &[Script::Construct(501), Script::Borrow(501, 7)],
        events: &[
            Event::Constructed(501),
            Event::Borrowed(501),
            Event::Finalized(501),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_success",
        source: include_str!("resource/11_later_handle_success.jett"),
        script: &[Script::Construct(503), Script::Borrow(503, 7)],
        events: &[
            Event::Constructed(503),
            Event::Borrowed(503),
            Event::Finalized(503),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_written_view",
        source: include_str!("resource/12_later_handle_written_view.jett"),
        script: &[Script::Construct(505), Script::Borrow(505, 7)],
        events: &[
            Event::Constructed(505),
            Event::Borrowed(505),
            Event::Finalized(505),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "first_handle_failure",
        source: include_str!("resource/13_first_handle_failure.jett"),
        script: &[Script::ConstructFail(506, "first sentinel")],
        events: &[Event::ConstructionFailed(506)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_cleanup_panic",
        source: include_str!("resource/09_later_handle_minimal.jett"),
        script: &[Script::FinalizerPanic(502)],
        events: &[Event::Constructed(502), Event::Finalized(502)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "first_handle_success",
        source: include_str!("resource/14_first_handle_success.jett"),
        script: &[Script::Construct(507), Script::Borrow(507, 7)],
        events: &[
            Event::Constructed(507),
            Event::Borrowed(507),
            Event::Finalized(507),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
];
