//! Identical original Source and finite script/oracle inputs for both test harnesses.
//! No record contains a runtime token, Resource key or installer authority.
#![allow(dead_code)] // Each harness consumes its own side of the shared observation oracle.
pub(crate) const SUPPORT: &str = include_str!("resource/resource_probe.jett");
#[derive(Clone, Copy, Debug)]
pub(crate) enum Script {
    Construct(i64),
    ConstructFail(i64, &'static str),
    FinalizerPanic(i64),
    Borrow(i64, i64),
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Event {
    Constructed(i64),
    ConstructionFailed(i64),
    Borrowed(i64),
    Finalized(i64),
}
#[derive(Clone, Copy, Debug)]
pub(crate) enum ReferenceOutcome {
    Clean,
    Error(&'static str),
    CleanupPanic(&'static str),
}
pub(crate) struct Case {
    pub(crate) name: &'static str,
    pub(crate) source: &'static str,
    pub(crate) script: &'static [Script],
    pub(crate) events: &'static [Event],
    pub(crate) reference: ReferenceOutcome,
    // Native status/channel literals are separate from the reference error representation.
    pub(crate) body: u32,
    pub(crate) cleanup: u32,
    pub(crate) channel: u32,
    pub(crate) ordinary_message: &'static [u8],
    pub(crate) resource_message: &'static [u8],
    pub(crate) exit: i32,
}
pub(crate) const CASES: &[Case] = &[
    Case {
        name: "connected",
        source: include_str!("resource/01_connected_entry.jett"),
        script: &[Script::Construct(1), Script::Borrow(1, 7)],
        events: &[
            Event::Constructed(1),
            Event::Borrowed(1),
            Event::Finalized(1),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "factory_fail",
        source: include_str!("resource/01_connected_entry.jett"),
        script: &[Script::ConstructFail(1, "declined")],
        events: &[Event::ConstructionFailed(1)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_actual",
        source: include_str!("resource/02_partial_actual_failure.jett"),
        script: &[Script::Construct(1)],
        events: &[Event::Constructed(1), Event::Finalized(1)],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
    Case {
        name: "implicit_drop",
        source: include_str!("resource/03_implicit_drop.jett"),
        script: &[Script::Construct(1)],
        events: &[Event::Constructed(1), Event::Finalized(1)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "finalizer_panic",
        source: include_str!("resource/03_implicit_drop.jett"),
        script: &[Script::FinalizerPanic(1)],
        events: &[Event::Constructed(1), Event::Finalized(1)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 0,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "replace_live",
        source: include_str!("resource/04_live_replace.jett"),
        script: &[
            Script::Construct(2401),
            Script::Construct(2402),
            Script::Borrow(2402, 7),
        ],
        events: &[
            Event::Constructed(2401),
            Event::Constructed(2402),
            Event::Finalized(2401),
            Event::Borrowed(2402),
            Event::Finalized(2402),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "rebind_self",
        source: include_str!("resource/05_self_rebind.jett"),
        script: &[Script::Construct(2421)],
        events: &[Event::Constructed(2421), Event::Finalized(2421)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "replace_closed",
        source: include_str!("resource/06_replace_closed.jett"),
        script: &[Script::Construct(2411), Script::Construct(2412)],
        events: &[
            Event::Constructed(2411),
            Event::Finalized(2411),
            Event::Constructed(2412),
            Event::Finalized(2412),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "rhs_domain_failure",
        source: include_str!("resource/07_rhs_domain_failure.jett"),
        script: &[
            Script::Construct(2431),
            Script::ConstructFail(2432, "rhs sentinel"),
            Script::Borrow(2431, 7),
        ],
        events: &[
            Event::Constructed(2431),
            Event::ConstructionFailed(2432),
            Event::Borrowed(2431),
            Event::Finalized(2431),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "rhs_ordinary_failure",
        source: include_str!("resource/08_rhs_ordinary_failure.jett"),
        script: &[Script::Construct(2441)],
        events: &[Event::Constructed(2441), Event::Finalized(2441)],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
    Case {
        name: "replace_old_finalizer_panic",
        source: include_str!("resource/04_live_replace.jett"),
        script: &[Script::FinalizerPanic(2401), Script::Construct(2402)],
        events: &[
            Event::Constructed(2401),
            Event::Constructed(2402),
            Event::Finalized(2401),
            Event::Finalized(2402),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "later_handle_minimal",
        source: include_str!("resource/09_later_handle_minimal.jett"),
        script: &[Script::Construct(502)],
        events: &[Event::Constructed(502), Event::Finalized(502)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_original",
        source: include_str!("resource/10_later_handle_original.jett"),
        script: &[Script::Construct(501), Script::Borrow(501, 7)],
        events: &[
            Event::Constructed(501),
            Event::Borrowed(501),
            Event::Finalized(501),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_success",
        source: include_str!("resource/11_later_handle_success.jett"),
        script: &[Script::Construct(503), Script::Borrow(503, 7)],
        events: &[
            Event::Constructed(503),
            Event::Borrowed(503),
            Event::Finalized(503),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_written_view",
        source: include_str!("resource/12_later_handle_written_view.jett"),
        script: &[Script::Construct(505), Script::Borrow(505, 7)],
        events: &[
            Event::Constructed(505),
            Event::Borrowed(505),
            Event::Finalized(505),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "first_handle_failure",
        source: include_str!("resource/13_first_handle_failure.jett"),
        script: &[Script::ConstructFail(506, "first sentinel")],
        events: &[Event::ConstructionFailed(506)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_cleanup_panic",
        source: include_str!("resource/09_later_handle_minimal.jett"),
        script: &[Script::FinalizerPanic(502)],
        events: &[Event::Constructed(502), Event::Finalized(502)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "first_handle_success",
        source: include_str!("resource/14_first_handle_success.jett"),
        script: &[Script::Construct(507), Script::Borrow(507, 7)],
        events: &[
            Event::Constructed(507),
            Event::Borrowed(507),
            Event::Finalized(507),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_two_owned_views",
        source: include_str!("resource/15_later_handle_two_owned_views.jett"),
        script: &[Script::Construct(511), Script::Construct(512)],
        events: &[
            Event::Constructed(511),
            Event::Constructed(512),
            Event::Finalized(512),
            Event::Finalized(511),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_return_other_owner",
        source: include_str!("resource/16_later_handle_return_other_owner.jett"),
        script: &[
            Script::Construct(521),
            Script::Construct(522),
            Script::Borrow(522, 7),
        ],
        events: &[
            Event::Constructed(521),
            Event::Constructed(522),
            Event::Finalized(521),
            Event::Borrowed(522),
            Event::Finalized(522),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_default",
        source: include_str!("resource/17_later_handle_default.jett"),
        script: &[Script::Construct(531), Script::Borrow(531, 7)],
        events: &[
            Event::Constructed(531),
            Event::Borrowed(531),
            Event::Finalized(531),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "later_handle_return_cleanup_panic",
        source: include_str!("resource/16_later_handle_return_other_owner.jett"),
        script: &[Script::FinalizerPanic(521), Script::Construct(522)],
        events: &[
            Event::Constructed(521),
            Event::Constructed(522),
            Event::Finalized(521),
            Event::Finalized(522),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "indirect_named_close",
        source: include_str!("resource/18_indirect_named_close.jett"),
        script: &[Script::Construct(701)],
        events: &[Event::Constructed(701), Event::Finalized(701)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "indirect_named_close_factory_fail",
        source: include_str!("resource/18_indirect_named_close.jett"),
        script: &[Script::ConstructFail(701, "indirect factory sentinel")],
        events: &[Event::ConstructionFailed(701)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "indirect_named_terminal_failure",
        source: include_str!("resource/19_indirect_named_terminal_failure.jett"),
        script: &[Script::Construct(701)],
        events: &[Event::Constructed(701), Event::Finalized(701)],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
    Case {
        name: "indirect_named_close_cleanup_panic",
        source: include_str!("resource/18_indirect_named_close.jett"),
        script: &[Script::FinalizerPanic(701)],
        events: &[Event::Constructed(701), Event::Finalized(701)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "indirect_named_terminal_cleanup_panic",
        source: include_str!("resource/19_indirect_named_terminal_failure.jett"),
        script: &[Script::FinalizerPanic(701)],
        events: &[Event::Constructed(701), Event::Finalized(701)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 1,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "indirect_named_alias",
        source: include_str!("resource/20_indirect_named_alias.jett"),
        script: &[Script::Construct(701)],
        events: &[Event::Constructed(701), Event::Finalized(701)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "indirect_namespace_close",
        source: include_str!("resource/21_indirect_namespace_close.jett"),
        script: &[Script::Construct(711)],
        events: &[Event::Constructed(711), Event::Finalized(711)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "indirect_namespace_close_factory_fail",
        source: include_str!("resource/21_indirect_namespace_close.jett"),
        script: &[Script::ConstructFail(711, "namespace factory sentinel")],
        events: &[Event::ConstructionFailed(711)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "indirect_namespace_close_cleanup_panic",
        source: include_str!("resource/21_indirect_namespace_close.jett"),
        script: &[Script::FinalizerPanic(711)],
        events: &[Event::Constructed(711), Event::Finalized(711)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "indirect_namespace_alias",
        source: include_str!("resource/22_indirect_namespace_alias.jett"),
        script: &[Script::Construct(711)],
        events: &[Event::Constructed(711), Event::Finalized(711)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_close",
        source: include_str!("resource/23_returned_hook_close.jett"),
        script: &[Script::Construct(721)],
        events: &[Event::Constructed(721), Event::Finalized(721)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_factory_fail",
        source: include_str!("resource/23_returned_hook_close.jett"),
        script: &[Script::ConstructFail(721, "returned hook factory sentinel")],
        events: &[Event::ConstructionFailed(721)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_cleanup_panic",
        source: include_str!("resource/23_returned_hook_close.jett"),
        script: &[Script::FinalizerPanic(721)],
        events: &[Event::Constructed(721), Event::Finalized(721)],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "returned_hook_alias",
        source: include_str!("resource/24_returned_hook_alias.jett"),
        script: &[Script::Construct(721)],
        events: &[Event::Constructed(721), Event::Finalized(721)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_relay",
        source: include_str!("resource/25_returned_hook_relay.jett"),
        script: &[Script::Construct(721)],
        events: &[Event::Constructed(721), Event::Finalized(721)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_unused",
        source: include_str!("resource/26_returned_hook_unused.jett"),
        script: &[],
        events: &[],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_factory",
        source: include_str!("resource/27_returned_hook_factory.jett"),
        script: &[Script::Construct(731)],
        events: &[Event::Constructed(731), Event::Finalized(731)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_factory_domain_fail",
        source: include_str!("resource/27_returned_hook_factory.jett"),
        script: &[Script::ConstructFail(731, "returned factory sentinel")],
        events: &[Event::ConstructionFailed(731)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "returned_hook_borrow",
        source: include_str!("resource/28_returned_hook_borrow.jett"),
        script: &[Script::Construct(741), Script::Borrow(741, 17)],
        events: &[
            Event::Constructed(741),
            Event::Borrowed(741),
            Event::Finalized(741),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "immediate_returned_hook_close",
        source: include_str!("resource/29_immediate_returned_hook_close.jett"),
        script: &[Script::Construct(751)],
        events: &[Event::Constructed(751), Event::Finalized(751)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "immediate_returned_hook_factory",
        source: include_str!("resource/30_immediate_returned_hook_factory.jett"),
        script: &[
            Script::Construct(742),
            Script::Construct(744),
            Script::Borrow(744, 743),
            Script::Borrow(742, 1),
            Script::Construct(743),
        ],
        events: &[
            Event::Constructed(742),
            Event::Constructed(744),
            Event::Borrowed(744),
            Event::Borrowed(742),
            Event::Constructed(743),
            Event::Finalized(743),
            Event::Finalized(744),
            Event::Finalized(742),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "immediate_returned_hook_factory_domain_fail",
        source: include_str!("resource/30_immediate_returned_hook_factory.jett"),
        script: &[
            Script::Construct(742),
            Script::Construct(744),
            Script::Borrow(744, 743),
            Script::Borrow(742, 1),
            Script::ConstructFail(743, "immediate returned factory sentinel"),
        ],
        events: &[
            Event::Constructed(742),
            Event::Constructed(744),
            Event::Borrowed(744),
            Event::Borrowed(742),
            Event::ConstructionFailed(743),
            Event::Finalized(744),
            Event::Finalized(742),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "immediate_returned_hook_callee_failure",
        source: include_str!("resource/31_immediate_returned_hook_callee_failure.jett"),
        script: &[
            Script::Construct(742),
            Script::Construct(744),
            Script::Borrow(744, 743),
            Script::Borrow(742, 1),
        ],
        events: &[
            Event::Constructed(742),
            Event::Constructed(744),
            Event::Borrowed(744),
            Event::Borrowed(742),
            Event::Finalized(744),
            Event::Finalized(742),
        ],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
    Case {
        name: "immediate_returned_hook_actual_failure",
        source: include_str!("resource/32_immediate_returned_hook_actual_failure.jett"),
        script: &[
            Script::Construct(742),
            Script::Construct(744),
            Script::Borrow(744, 743),
        ],
        events: &[
            Event::Constructed(742),
            Event::Constructed(744),
            Event::Borrowed(744),
            Event::Finalized(744),
            Event::Finalized(742),
        ],
        reference: ReferenceOutcome::Error("list.__remove_at: index -1 out of bounds"),
        body: 1,
        cleanup: 0,
        channel: 1,
        ordinary_message: b"list.__remove_at: index -1 out of bounds",
        resource_message: b"native Resource protocol refused",
        exit: 71,
    },
];
