//! Shared proposed reflected body/owned Return observations; no custody authority.
//! All new Source/completion oracles require actual reference/native gates.
use super::cases::{Case, Event, ReferenceOutcome, Script};

const BODY_SOURCE: &str = include_str!(
    "../../../jett_comptime/src/resource_execution/tests/native_source_oracles/source06_exceptional/10_reflected_field_successful_return.jett"
);
const OWNED_SOURCE: &str = include_str!(
    "../../../jett_comptime/src/resource_execution/tests/native_source_oracles/source06_exceptional/11_reflected_field_owned_return.jett"
);

pub(super) const CASES: &[Case] = &[
    Case {
        name: "reflected_body_return_first_ready",
        source: BODY_SOURCE,
        script: &[Script::Construct(881), Script::Borrow(881, 17)],
        events: &[
            Event::Constructed(881),
            Event::Borrowed(881),
            Event::Finalized(881),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_body_return_second_ready",
        source: BODY_SOURCE,
        script: &[
            Script::Construct(881),
            Script::Borrow(881, 11),
            Script::Borrow(881, 17),
        ],
        events: &[
            Event::Constructed(881),
            Event::Borrowed(881),
            Event::Borrowed(881),
            Event::Finalized(881),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_body_return_first_borrow_fail",
        source: BODY_SOURCE,
        script: &[
            Script::Construct(881),
            Script::BorrowFail(881, "borrow sentinel"),
        ],
        events: &[
            Event::Constructed(881),
            Event::BorrowFailed(881),
            Event::Finalized(881),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_body_return_second_borrow_fail",
        source: BODY_SOURCE,
        script: &[
            Script::Construct(881),
            Script::Borrow(881, 11),
            Script::BorrowFail(881, "later borrow sentinel"),
        ],
        events: &[
            Event::Constructed(881),
            Event::Borrowed(881),
            Event::BorrowFailed(881),
            Event::Finalized(881),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_body_return_second_cleanup_panic",
        source: BODY_SOURCE,
        script: &[
            Script::FinalizerPanic(881),
            Script::Borrow(881, 11),
            Script::Borrow(881, 17),
        ],
        events: &[
            Event::Constructed(881),
            Event::Borrowed(881),
            Event::Borrowed(881),
            Event::Finalized(881),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 0,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "reflected_body_return_handled_failure_cleanup_panic",
        source: BODY_SOURCE,
        script: &[
            Script::FinalizerPanic(881),
            Script::BorrowFail(881, "borrow sentinel"),
        ],
        events: &[
            Event::Constructed(881),
            Event::BorrowFailed(881),
            Event::Finalized(881),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 0,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "reflected_owned_return_first_ready",
        source: OWNED_SOURCE,
        script: &[
            Script::Construct(891),
            Script::Construct(892),
            Script::Borrow(891, 17),
            Script::Borrow(892, 29),
        ],
        events: &[
            Event::Constructed(891),
            Event::Constructed(892),
            Event::Borrowed(891),
            Event::Finalized(891),
            Event::Borrowed(892),
            Event::Finalized(892),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_owned_return_second_ready",
        source: OWNED_SOURCE,
        script: &[
            Script::Construct(891),
            Script::Construct(892),
            Script::Borrow(891, 11),
            Script::Borrow(891, 17),
            Script::Borrow(892, 29),
        ],
        events: &[
            Event::Constructed(891),
            Event::Constructed(892),
            Event::Borrowed(891),
            Event::Borrowed(891),
            Event::Finalized(891),
            Event::Borrowed(892),
            Event::Finalized(892),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_owned_return_first_borrow_fail",
        source: OWNED_SOURCE,
        script: &[
            Script::Construct(891),
            Script::Construct(892),
            Script::BorrowFail(891, "borrow sentinel"),
            Script::Borrow(892, 29),
        ],
        events: &[
            Event::Constructed(891),
            Event::Constructed(892),
            Event::BorrowFailed(891),
            Event::Finalized(891),
            Event::Borrowed(892),
            Event::Finalized(892),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_owned_return_second_borrow_fail",
        source: OWNED_SOURCE,
        script: &[
            Script::Construct(891),
            Script::Construct(892),
            Script::Borrow(891, 11),
            Script::BorrowFail(891, "later borrow sentinel"),
            Script::Borrow(892, 29),
        ],
        events: &[
            Event::Constructed(891),
            Event::Constructed(892),
            Event::Borrowed(891),
            Event::BorrowFailed(891),
            Event::Finalized(891),
            Event::Borrowed(892),
            Event::Finalized(892),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_owned_return_cleanup_suppresses_publication",
        source: OWNED_SOURCE,
        script: &[
            Script::FinalizerPanic(891),
            Script::Construct(892),
            Script::Borrow(891, 17),
        ],
        events: &[
            Event::Constructed(891),
            Event::Constructed(892),
            Event::Borrowed(891),
            Event::Finalized(891),
            Event::Finalized(892),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "reflected_owned_return_handled_failure_cleanup_suppresses_publication",
        source: OWNED_SOURCE,
        script: &[
            Script::FinalizerPanic(891),
            Script::Construct(892),
            Script::Borrow(891, 11),
            Script::BorrowFail(891, "later borrow sentinel"),
        ],
        events: &[
            Event::Constructed(891),
            Event::Constructed(892),
            Event::Borrowed(891),
            Event::BorrowFailed(891),
            Event::Finalized(891),
            Event::Finalized(892),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
];

pub(super) fn ready_for(case: &Case) -> &'static Case {
    if case.source == BODY_SOURCE {
        &CASES[0]
    } else {
        assert_eq!(case.source, OWNED_SOURCE);
        &CASES[6]
    }
}
