//! Standalone reflected-field Sources; existing191case catalog remains unchanged.
//! Exact tuples are checked by single-entry and same-grant native execution.
use super::cases::{Case, Event, ReferenceOutcome, Script};

const READY_SCRIPT: &[Script] = &[
    Script::Construct(871),
    Script::Borrow(871, 17),
    Script::Borrow(871, 17),
];
const READY_EVENTS: &[Event] = &[
    Event::Constructed(871),
    Event::Borrowed(871),
    Event::Borrowed(871),
    Event::Finalized(871),
];
pub(crate) const CASES: &[Case] = &[
    Case {
        name: "reflected_field_original",
        source: include_str!("resource/reflected_field_native/01_original.jett"),
        script: READY_SCRIPT,
        events: READY_EVENTS,
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_field_index_distinct",
        source: include_str!("resource/reflected_field_native/02_index_distinct.jett"),
        script: READY_SCRIPT,
        events: READY_EVENTS,
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_field_name_distinct",
        source: include_str!("resource/reflected_field_native/03_name_distinct.jett"),
        script: READY_SCRIPT,
        events: READY_EVENTS,
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_field_ordinary_helper",
        source: include_str!("resource/reflected_field_native/04_ordinary_helper.jett"),
        script: READY_SCRIPT,
        events: READY_EVENTS,
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
];

// Exact original Source06 scripts from its checked exceptional reference gate.
// Native statuses/messages use the existing matched-launcher completion contract;
// these new enclosing cases require linked execution before acceptance.
const SOURCE06: &str = include_str!("resource/reflected_field_native/01_original.jett");
pub(crate) const SOURCE06_EXCEPTIONAL_CASES: &[Case] = &[
    Case {
        name: "reflected_field_construct_fail",
        source: SOURCE06,
        script: &[Script::ConstructFail(871, "nested factory sentinel")],
        events: &[Event::ConstructionFailed(871)],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_field_first_borrow_fail",
        source: SOURCE06,
        script: &[
            Script::Construct(871),
            Script::BorrowFail(871, "borrow sentinel"),
        ],
        events: &[
            Event::Constructed(871),
            Event::BorrowFailed(871),
            Event::Finalized(871),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_field_later_borrow_fail",
        source: SOURCE06,
        script: &[
            Script::Construct(871),
            Script::Borrow(871, 17),
            Script::BorrowFail(871, "later borrow sentinel"),
        ],
        events: &[
            Event::Constructed(871),
            Event::Borrowed(871),
            Event::BorrowFailed(871),
            Event::Finalized(871),
        ],
        reference: ReferenceOutcome::Clean,
        body: 0,
        cleanup: 0,
        channel: 0,
        ordinary_message: b"",
        resource_message: b"",
        exit: 0,
    },
    Case {
        name: "reflected_field_ready_cleanup_panic",
        source: SOURCE06,
        script: &[
            Script::FinalizerPanic(871),
            Script::Borrow(871, 17),
            Script::Borrow(871, 17),
        ],
        events: READY_EVENTS,
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 255,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "reflected_field_first_borrow_provider_panic",
        source: SOURCE06,
        script: &[Script::Construct(871), Script::BorrowPanic(871)],
        events: &[
            Event::Constructed(871),
            Event::Borrowed(871),
            Event::Finalized(871),
        ],
        reference: ReferenceOutcome::ProviderPanic("selected test borrow provider panic"),
        body: 1,
        cleanup: 0,
        channel: 2,
        ordinary_message: b"",
        resource_message: b"runtime operation panicked",
        exit: 73,
    },
    Case {
        name: "reflected_field_later_borrow_provider_panic",
        source: SOURCE06,
        script: &[
            Script::Construct(871),
            Script::Borrow(871, 17),
            Script::BorrowPanic(871),
        ],
        events: READY_EVENTS,
        reference: ReferenceOutcome::ProviderPanic("selected test borrow provider panic"),
        body: 1,
        cleanup: 0,
        channel: 2,
        ordinary_message: b"",
        resource_message: b"runtime operation panicked",
        exit: 73,
    },
    Case {
        name: "reflected_field_cleanup_wins_provider_panic",
        source: SOURCE06,
        script: &[Script::FinalizerPanic(871), Script::BorrowPanic(871)],
        events: &[
            Event::Constructed(871),
            Event::Borrowed(871),
            Event::Finalized(871),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 1,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
    Case {
        name: "reflected_field_cleanup_wins_domain_failure_return",
        source: SOURCE06,
        script: &[
            Script::FinalizerPanic(871),
            Script::BorrowFail(871, "borrow sentinel"),
        ],
        events: &[
            Event::Constructed(871),
            Event::BorrowFailed(871),
            Event::Finalized(871),
        ],
        reference: ReferenceOutcome::CleanupPanic("selected test resource cleanup panic"),
        body: 0,
        cleanup: 255,
        channel: 3,
        ordinary_message: b"",
        resource_message: b"native Resource cleanup failed",
        exit: 71,
    },
];
