"""Authoring source for 30 ASCII text benchmarks and equivalent typed adapters.

This file is evaluator material, never part of model prompts or language skills.
The small typed AST emitter preserves one algorithm across five baseline languages;
fixed expected fixtures are independently specified below, not generated by solving.
"""
from __future__ import annotations

import ast
import copy
import json
import re
import shutil
import subprocess
from pathlib import Path
from dataclasses import dataclass

ROOT = Path(__file__).resolve().parents[1]
LANGS = {"jett": "jett", "python": "py", "typescript": "ts", "go": "go", "rust": "rs"}
TYPES = {
    "jett": {"str": "string", "int": "int64", "bool": "bool", "Outcome": "TextOutcome", "Pair": "TextPair", "Words":"list[string]"},
    "python": {"str": "str", "int": "int", "bool": "bool", "Outcome": "TextOutcome", "Pair": "TextPair", "Words":"list[str]"},
    "typescript": {"str": "string", "int": "number", "bool": "boolean", "Outcome": "TextOutcome", "Pair": "TextPair", "Words":"string[]"},
    "go": {"str": "string", "int": "int64", "bool": "bool", "Outcome": "TextOutcome", "Pair": "TextPair", "Words":"[]string"},
    "rust": {"str": "String", "int": "i64", "bool": "bool", "Outcome": "TextOutcome", "Pair": "TextPair", "Words":"Vec<String>"},
}

@dataclass
class Task:
    name: str
    statement: str
    source: str
    cases: list[tuple[tuple[object, ...], object]]

TASKS: list[Task] = []
NUMERIC_TASKS = {"binary_parse", "ipv4_parse", "time_parse"}

def task(name: str, statement: str, source: str, cases: list[tuple[tuple[object, ...], object]]) -> None:
    assert len(cases) >= 10, name
    TASKS.append(Task(name, statement, source.strip() + "\n", cases))

HELPERS = '''
def digit(ch: str) -> int:
    pos: int = 0
    while pos < 10:
        if at("0123456789", pos) == ch:
            return pos
        pos = pos + 1
    return -1

def hex_digit(ch: str) -> int:
    pos: int = 0
    while pos < 16:
        if at("0123456789abcdef", pos) == lower(ch):
            return pos
        pos = pos + 1
    return -1

def alpha(ch: str) -> bool:
    return contains("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", ch) and length(ch) == 1

def alnum(ch: str) -> bool:
    return alpha(ch) or digit(ch) >= 0

def compact(text: str) -> str:
    out: str = ""
    pending: bool = False
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if ch == " ":
            pending = length(out) > 0
        else:
            if pending:
                out = out + " "
            out = out + ch
            pending = False
        pos = pos + 1
    return out

def uint_value(text: str, bound: int) -> int:
    if length(text) == 0:
        return -1
    value: int = 0
    pos: int = 0
    while pos < length(text):
        num: int = digit(at(text, pos))
        if num < 0:
            return -1
        value = value * 10 + num
        if value > bound:
            return -1
        pos = pos + 1
    return value

def ascii_print(code: int) -> str:
    return at(" !\\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~", code - 32)

def pair_label(first: str, second: str) -> str:
    return render(length(first)) + ":" + first + render(length(second)) + ":" + second
'''

def single(items: list[tuple[object, object]]) -> list[tuple[tuple[object, ...], object]]:
    return [((x,), y) for x, y in items]

task("collapse_spaces", "Collapse runs of ASCII space U+0020 to one space and remove leading/trailing spaces. Preserve all other ASCII characters, including tabs and newlines.", '''
def solve(text: str) -> str:
    return compact(text)
''', single([("", ""), (" ", ""), ("   ", ""), ("a", "a"), (" a ", "a"), ("a  b", "a b"), (" a  b c ", "a b c"), ("a\tb", "a\tb"), (" \t ", "\t"), ("a\n  b", "a\n b"), ("!  ?", "! ?"), (" x   x  x ", "x x x")]))
task("ascii_identifier", "Return whether text is a nonempty ASCII identifier: first character is a letter or underscore; remaining characters are letters, digits, or underscores. Keywords have no special status.", '''
def solve(text: str) -> bool:
    if length(text) == 0:
        return False
    first: str = at(text, 0)
    if not alpha(first) and first != "_":
        return False
    pos: int = 1
    while pos < length(text):
        ch: str = at(text, pos)
        if not alnum(ch) and ch != "_":
            return False
        pos = pos + 1
    return True
''', single([("",False),("_",True),("a",True),("A0_z",True),("0a",False),("a-b",False),("a b",False),("if",True),("__",True),("a\n",False),("$a",False),("z9",True)]))
task("camel_to_snake", "Convert an ASCII identifier containing only letters and digits to lowercase snake case. Insert underscore before uppercase when preceded by lowercase/digit, or when preceded by uppercase and followed by lowercase. Empty input returns empty.", '''
def boundary(text: str, pos: int) -> bool:
    if pos == 0:
        return False
    ch: str = at(text, pos)
    if not contains("ABCDEFGHIJKLMNOPQRSTUVWXYZ", ch):
        return False
    prev: str = at(text, pos - 1)
    if contains("abcdefghijklmnopqrstuvwxyz0123456789", prev):
        return True
    return contains("abcdefghijklmnopqrstuvwxyz", at(text, pos + 1)) and pos + 1 < length(text)

def solve(text: str) -> str:
    out: str = ""
    pos: int = 0
    while pos < length(text):
        if boundary(text, pos):
            out = out + "_"
        out = out + lower(at(text, pos))
        pos = pos + 1
    return out
''', single([("",""),("a","a"),("A","a"),("camelCase","camel_case"),("HTTPServer","http_server"),("XML","xml"),("parseURLValue","parse_url_value"),("x2Y","x2_y"),("ABc","a_bc"),("oneTwoThree","one_two_three"),("v123","v123"),("ABCdEF","ab_cd_ef")]))
task("word_initials", "Words are maximal non-space ASCII runs separated only by U+0020. Return the uppercase first character of each word, concatenated. Preserve punctuation/digits when they are initials.", '''
def solve(text: str) -> str:
    out: str = ""
    start: bool = True
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if ch == " ":
            start = True
        else:
            if start:
                out = out + upper(ch)
            start = False
        pos = pos + 1
    return out
''', single([("",""),("  ",""),("alice","A"),("alice bob","AB"),("  alice   bob ","AB"),("a b c","ABC"),("1 one","1O"),("! bang","!B"),("mixed CASE","MC"),("a\tb c","AC"),("z Z","ZZ"),("foo-bar baz","FB")]))
task("title_words", "Words are maximal non-space ASCII runs separated only by U+0020. Lowercase each word and uppercase its first character. Preserve every original ASCII space exactly.", '''
def solve(text: str) -> str:
    out: str = ""
    start: bool = True
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if ch == " ":
            out = out + ch
            start = True
        else:
            if start:
                out = out + upper(ch)
            else:
                out = out + lower(ch)
            start = False
        pos = pos + 1
    return out
''', single([("",""),(" "," "),("HELLO","Hello"),("hello WORLD","Hello World"),("  a  B ","  A  B "),("a-b","A-b"),("1ABC","1abc"),("!HELLO","!hello"),("x\tY","X\ty"),("a b c","A B C"),("MiXeD","Mixed"),("A  B  C","A  B  C")]))
task("reverse_words", "Reverse the order of maximal non-space ASCII words, joining with one U+0020 space and removing outer spaces. Do not reverse characters within words.", '''
def solve(text: str) -> str:
    clean: str = compact(text)
    out: str = ""
    end: int = length(clean)
    pos: int = length(clean) - 1
    while pos >= 0:
        if at(clean, pos) == " ":
            out = out + part(clean, pos + 1, end) + " "
            end = pos
        pos = pos - 1
    return out + part(clean, 0, end)
''', single([("",""),(" ",""),("a","a"),("a b","b a"),(" a  b c ","c b a"),("one two three","three two one"),("a a b","b a a"),("! ?","? !"),("a\tb c","c a\tb"),("word  ","word"),("  x","x"),("ab cd ef gh","gh ef cd ab")]))
task("longest_word", "Return accepted(value) holding the longest maximal non-space ASCII word; ties choose the earliest word. Return rejected(empty) when there are no words. Spaces are U+0020 only.", '''
def solve(text: str) -> Outcome:
    best: str = ""
    word: str = ""
    pos: int = 0
    while pos <= length(text):
        ch: str = at(text, pos)
        if ch == " " or pos == length(text):
            if length(word) > length(best):
                best = word
            word = ""
        else:
            word = word + ch
        pos = pos + 1
    if best == "":
        return rejected("empty")
    return accepted(best)
''', single([("",("rejected","empty")),("  ",("rejected","empty")),("a",("accepted","a")),("a bb c",("accepted","bb")),("ab cd",("accepted","ab")),(" xxx yy ",("accepted","xxx")),("a\tb zz",("accepted","a\tb")),("! ??",("accepted","??")),("long short",("accepted","short")),("same same",("accepted","same")),("   end",("accepted","end")),("ab abc abcd",("accepted","abcd"))]))
task("palindrome_filter", "Discard every ASCII character except letters and digits, lowercase the remaining letters, then return whether that sequence is a palindrome. Empty filtered text is a palindrome.", '''
def solve(text: str) -> bool:
    clean: str = ""
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if alnum(ch):
            clean = clean + lower(ch)
        pos = pos + 1
    pos = 0
    while pos < length(clean):
        if at(clean, pos) != at(clean, length(clean) - 1 - pos):
            return False
        pos = pos + 1
    return True
''', single([("",True),("! ?",True),("a",True),("ab",False),("Aa",True),("Race car!",True),("A man, a plan, a canal: Panama",True),("12 21",True),("12a21",True),("12a22",False),("0P",False),("ab\tBA",True)]))
task("common_prefix", "Return the longest exact case-sensitive common prefix of two ASCII strings.", '''
def solve(left: str, right: str) -> str:
    pos: int = 0
    while pos < length(left) and pos < length(right):
        if at(left, pos) != at(right, pos):
            return part(left, 0, pos)
        pos = pos + 1
    return part(left, 0, pos)
''', [(("",""),""),(("a",""),""),(("","a"),""),(("abc","abc"),"abc"),(("abc","abd"),"ab"),(("abc","ab"),"ab"),(("ab","abc"),"ab"),(("a","A"),""),(("foo bar","foo baz"),"foo ba"),((" x"," y")," "),(("123","129"),"12"),(("abc","zabc"),"")])
task("count_overlaps", "Count all start positions at which needle occurs in text, including overlapping occurrences. An empty needle occurs at all length(text)+1 boundaries. Exact case-sensitive ASCII comparison.", '''
def solve(text: str, needle: str) -> int:
    count: int = 0
    pos: int = 0
    while pos + length(needle) <= length(text):
        if part(text, pos, pos + length(needle)) == needle:
            count = count + 1
        pos = pos + 1
    return count
''', [(("",""),1),(("","a"),0),(("abc",""),4),(("aaaa","aa"),3),(("ababa","aba"),2),(("abc","abc"),1),(("ab","abc"),0),(("AaA","a"),1),(("xxxxx","xx"),4),(("one one","one"),2),((" "," "),1),(("abc","z"),0)])
task("bracket_balance", "Return whether the (), [], and {} brackets in an ASCII string are correctly nested and balanced. Ignore all other characters; quotes have no special meaning.", '''
def closing(ch: str) -> str:
    if ch == ")":
        return "("
    if ch == "]":
        return "["
    return "{"

def solve(text: str) -> bool:
    stack: str = ""
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if contains("([{", ch):
            stack = stack + ch
        else:
            if contains(")]}", ch):
                if length(stack) == 0:
                    return False
                if at(stack, length(stack) - 1) != closing(ch):
                    return False
                stack = part(stack, 0, length(stack) - 1)
        pos = pos + 1
    return stack == ""
''', single([("",True),("abc",True),("()[]{}",True),("([{}])",True),("([)]",False),("(",False),(")",False),("a[b(c)d]e",True),("{{}}",True),("{]",False),("\"(\"",False),("(()())",True)]))
task("strip_line_comments", "Remove each # and all following characters until newline when # is outside double quotes. Preserve newlines and quoted text. Inside double quotes backslash protects the next character; outside quotes it has no special meaning. Unclosed quotes simply continue through end of input.", '''
def quote_mode(mode: int, ch: str) -> int:
    if mode == 2:
        return 1
    if mode == 1 and ch == "\\\\":
        return 2
    if ch == "\\\"":
        return 1 - mode
    return mode

def solve(text: str) -> str:
    out: str = ""
    mode: int = 0
    comment: bool = False
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if comment:
            if ch == "\\n":
                comment = False
                out = out + ch
        else:
            if mode == 0 and ch == "#":
                comment = True
            else:
                out = out + ch
                mode = quote_mode(mode, ch)
        pos = pos + 1
    return out
''', single([("",""),("abc","abc"),("#x",""),("a#b","a"),("a#b\nc","a\nc"),("\"#x\"#y","\"#x\""),("#a\n#b\n","\n\n"),("a # x","a "),("\"a\\\"#b\"#c","\"a\\\"#b\""),("\\#x","\\"),("\"#open","\"#open"),("a\n#x\nb","a\n\nb")]))
task("escape_html", "Escape ASCII text for a double-quoted HTML attribute: & becomes &amp;, < becomes &lt;, > becomes &gt;, double quote becomes &quot;, apostrophe becomes &#39;. Preserve all other characters. Existing entities are escaped again.", '''
def escape_char(ch: str) -> str:
    if ch == "&":
        return "&amp;"
    if ch == "<":
        return "&lt;"
    if ch == ">":
        return "&gt;"
    if ch == "\\\"":
        return "&quot;"
    if ch == "'":
        return "&#39;"
    return ch

def solve(text: str) -> str:
    out: str = ""
    pos: int = 0
    while pos < length(text):
        out = out + escape_char(at(text, pos))
        pos = pos + 1
    return out
''', single([("",""),("abc","abc"),("&","&amp;"),("<>","&lt;&gt;"),("\"'","&quot;&#39;"),("&amp;","&amp;amp;"),("a&b<c","a&amp;b&lt;c"),("&&","&amp;&amp;"),("\n\t","\n\t"),("/a=1","/a=1"),("<a x=\"b\">","&lt;a x=&quot;b&quot;&gt;"),("'&'","&#39;&amp;&#39;")]))
task("escape_json_string", "Return a quoted JSON string literal. Input ASCII is limited to printable characters plus newline, tab, carriage return, backspace, and form feed. Escape double quote, backslash, and those five controls using the short JSON escapes; do not escape slash.", '''
def escape_char(ch: str) -> str:
    if ch == "\\\"":
        return "\\\\\\\""
    if ch == "\\\\":
        return "\\\\\\\\"
    if ch == "\\n":
        return "\\\\n"
    if ch == "\\t":
        return "\\\\t"
    if ch == "\\r":
        return "\\\\r"
    if ch == "\\b":
        return "\\\\b"
    if ch == "\\f":
        return "\\\\f"
    return ch

def solve(text: str) -> str:
    out: str = "\\\""
    pos: int = 0
    while pos < length(text):
        out = out + escape_char(at(text, pos))
        pos = pos + 1
    return out + "\\\""
''', single([("",'""'),("a",'"a"'),('"','"\\\""'),('\\','"\\\\"'),('\n','"\\n"'),('\t','"\\t"'),('\r','"\\r"'),('\b','"\\b"'),('\f','"\\f"'),('/','"/"'),('a"b\\c','"a\\\"b\\\\c"'),('x\ny\tz','"x\\ny\\tz"')]))
task("unescape_backslash", "Decode backslash escapes n, t, r, backslash, and double quote in ASCII text. Ordinary characters pass through. Return rejected(malformed) for a final lone backslash or any unsupported escape; otherwise accepted(decoded text).", '''
def decode_escape(ch: str) -> str:
    if ch == "n":
        return "\\n"
    if ch == "t":
        return "\\t"
    if ch == "r":
        return "\\r"
    return ch

def solve(text: str) -> Outcome:
    out: str = ""
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if ch == "\\\\":
            pos = pos + 1
            if pos == length(text):
                return rejected("malformed")
            ch = at(text, pos)
            if not contains("ntr\\\\\\\"", ch):
                return rejected("malformed")
            ch = decode_escape(ch)
        out = out + ch
        pos = pos + 1
    return accepted(out)
''', single([("",("accepted","")),("abc",("accepted","abc")),("\\n",("accepted","\n")),("\\t\\r",("accepted","\t\r")),("\\\\",("accepted","\\")),('\\"',("accepted",'"')),("a\\nb",("accepted","a\nb")),("\\",("rejected","malformed")),("x\\q",("rejected","malformed")),("\\0",("rejected","malformed")),("\\\\n",("accepted","\\n")),("a\nb",("accepted","a\nb"))]))
task("percent_decode", "Decode %HH pairs (case-insensitive hexadecimal) to printable ASCII U+0020..U+007E. Ordinary printable ASCII including + passes through unchanged. Return rejected(malformed) for an incomplete/nonhex escape; rejected(range) for a decoded nonprintable byte. Process left to right and return the first error.", '''
def solve(text: str) -> Outcome:
    out: str = ""
    pos: int = 0
    while pos < length(text):
        ch: str = at(text, pos)
        if ch == "%":
            if pos + 2 >= length(text):
                return rejected("malformed")
            high: int = hex_digit(at(text, pos + 1))
            low: int = hex_digit(at(text, pos + 2))
            if high < 0 or low < 0:
                return rejected("malformed")
            code: int = high * 16 + low
            if code < 32 or code > 126:
                return rejected("range")
            ch = ascii_print(code)
            pos = pos + 2
        out = out + ch
        pos = pos + 1
    return accepted(out)
''', single([("",("accepted","")),("abc",("accepted","abc")),("a+b",("accepted","a+b")),("%41%20%7e",("accepted","A ~")),("%25",("accepted","%")),("%",("rejected","malformed")),("%2",("rejected","malformed")),("%GG",("rejected","malformed")),("%00",("rejected","range")),("%7F",("rejected","range")),("%ff",("rejected","range")),("%00%G0",("rejected","range")),("%G0%00",("rejected","malformed")),("x%2fy",("accepted","x/y"))]))
task("hex_decode", "Decode an even-length string of case-insensitive hexadecimal digits to printable ASCII U+0020..U+007E. Empty input is accepted. Validate even length first, then pairs left to right; reject malformed for nonhex digits or odd length, and range for decoded nonprintable bytes.", '''
def solve(text: str) -> Outcome:
    if length(text) % 2 != 0:
        return rejected("malformed")
    out: str = ""
    pos: int = 0
    while pos < length(text):
        high: int = hex_digit(at(text, pos))
        low: int = hex_digit(at(text, pos + 1))
        if high < 0 or low < 0:
            return rejected("malformed")
        code: int = high * 16 + low
        if code < 32 or code > 126:
            return rejected("range")
        out = out + ascii_print(code)
        pos = pos + 2
    return accepted(out)
''', single([("",("accepted","")),("41",("accepted","A")),("6869",("accepted","hi")),("207E",("accepted"," ~")),("5c22",("accepted",'\\"')),("0",("rejected","malformed")),("GG",("rejected","malformed")),("00",("rejected","range")),("7f",("rejected","range")),("ff",("rejected","range")),("00g",("rejected","malformed")),("002G",("rejected","range")),("2G00",("rejected","malformed"))]))
task("binary_parse", "Parse a nonempty ASCII binary string of at most 16 characters. Leading zeros are allowed. Validate length first: empty is rejected(empty), length above 16 is rejected(range). Then nonbinary characters are rejected(malformed). Accepted value is its nonnegative integer value.", '''
def solve(text: str) -> Outcome:
    if length(text) == 0:
        return rejected("empty")
    if length(text) > 16:
        return rejected("range")
    value: int = 0
    pos: int = 0
    while pos < length(text):
        num: int = digit(at(text, pos))
        if num < 0 or num > 1:
            return rejected("malformed")
        value = value * 2 + num
        pos = pos + 1
    return accepted(render(value))
''', single([("",("rejected","empty")),("0",("accepted","0")),("1",("accepted","1")),("00101",("accepted","5")),("1111111111111111",("accepted","65535")),("1000000000000000",("accepted","32768")),("00000000000000000",("rejected","range")),("2",("rejected","malformed")),("10x",("rejected","malformed")),(" 1",("rejected","malformed")),("+1",("rejected","malformed")),("101010",("accepted","42")),("x"*17,("rejected","range"))]))
task("decimal_canonical", "Canonicalize an optionally signed ASCII decimal integer containing at most 100 digits (input length at most 101). A sign may be + or -. Leading zeros are accepted and removed; every zero is rendered 0. Reject empty input with empty; reject missing digits or any nondigit with malformed. No arithmetic overflow: operate on digit text.", '''
def signed_digits(negative: bool, digits: str) -> Outcome:
    if digits == "":
        return accepted("0")
    if negative:
        return accepted("-" + digits)
    return accepted(digits)

def solve(text: str) -> Outcome:
    if length(text) == 0:
        return rejected("empty")
    pos: int = 0
    negative: bool = at(text, 0) == "-"
    if negative or at(text, 0) == "+":
        pos = 1
    if pos == length(text):
        return rejected("malformed")
    out: str = ""
    while pos < length(text):
        ch: str = at(text, pos)
        if digit(ch) < 0:
            return rejected("malformed")
        if out != "" or ch != "0":
            out = out + ch
        pos = pos + 1
    return signed_digits(negative, out)
''', single([("",("rejected","empty")),("0",("accepted","0")),("-000",("accepted","0")),("+0012",("accepted","12")),("-012",("accepted","-12")),("123",("accepted","123")),("+",("rejected","malformed")),("--1",("rejected","malformed")),(" 1",("rejected","malformed")),("1.0",("rejected","malformed")),("0x0",("rejected","malformed")),("9"*100,("accepted","9"*100)),("-"+"0"*99+"1",("accepted","-1"))]))
task("ipv4_parse", "Validate exactly four canonical decimal IPv4 octets separated by dots. Each octet is 0..255, has no sign or whitespace, and has no leading zero unless it is 0. Return accepted holding its unsigned 32-bit numeric value in the declared integer field (0..4294967295); return rejected(malformed) for any invalid input.", '''
def octet(text: str) -> int:
    if length(text) > 1 and at(text, 0) == "0":
        return -1
    return uint_value(text, 255)

def solve(text: str) -> Outcome:
    pos: int = 0
    start: int = 0
    count: int = 0
    value: int = 0
    while pos <= length(text):
        if pos == length(text) or at(text, pos) == ".":
            num: int = octet(part(text, start, pos))
            if num < 0 or count == 4:
                return rejected("malformed")
            value = value * 256 + num
            count = count + 1
            start = pos + 1
        pos = pos + 1
    if count != 4:
        return rejected("malformed")
    return accepted(render(value))
''', single([("0.0.0.0",("accepted","0")),("255.255.255.255",("accepted","4294967295")),("127.0.0.1",("accepted","2130706433")),("192.168.1.1",("accepted","3232235777")),("1.2.3.4",("accepted","16909060")),("",("rejected","malformed")),("1.2.3",("rejected","malformed")),("1.2.3.4.5",("rejected","malformed")),("01.2.3.4",("rejected","malformed")),("256.0.0.1",("rejected","malformed")),("1..2.3",("rejected","malformed")),("1.2.3.-1",("rejected","malformed")),("1.2.3.4 ",("rejected","malformed"))]))
task("time_parse", "Parse exact ASCII HH:MM:SS with two decimal digits per component. Hours range 00..23, minutes and seconds 00..59. Validate shape/digits first (malformed), then ranges (range). Accepted integer value is seconds since midnight.", '''
def solve(text: str) -> Outcome:
    if length(text) != 8:
        return rejected("malformed")
    if at(text, 2) != ":" or at(text, 5) != ":":
        return rejected("malformed")
    hour: int = uint_value(part(text, 0, 2), 99)
    minute: int = uint_value(part(text, 3, 5), 99)
    second: int = uint_value(part(text, 6, 8), 99)
    if hour < 0 or minute < 0 or second < 0:
        return rejected("malformed")
    if hour > 23 or minute > 59 or second > 59:
        return rejected("range")
    return accepted(render(hour * 3600 + minute * 60 + second))
''', single([("00:00:00",("accepted","0")),("23:59:59",("accepted","86399")),("12:34:56",("accepted","45296")),("01:02:03",("accepted","3723")),("24:00:00",("rejected","range")),("00:60:00",("rejected","range")),("00:00:60",("rejected","range")),("0:00:00",("rejected","malformed")),("00-00-00",("rejected","malformed")),("aa:00:00",("rejected","malformed")),("99:xx:00",("rejected","malformed")),("",("rejected","malformed"))]))
task("version_compare", "Compare two version strings, each guaranteed 1..8 dot-separated canonical decimal components in 0..999. Missing trailing components count as zero. Return -1, 0, or 1 according to numeric lexicographic component comparison.", '''
def component_end(text: str, start: int) -> int:
    pos: int = start
    while pos < length(text):
        if at(text, pos) == ".":
            return pos
        pos = pos + 1
    return pos

def component_value(text: str, start: int, end: int) -> int:
    if start >= length(text):
        return 0
    return uint_value(part(text, start, end), 999)

def solve(left: str, right: str) -> int:
    lp: int = 0
    rp: int = 0
    while lp < length(left) or rp < length(right):
        le: int = component_end(left, lp)
        re: int = component_end(right, rp)
        lv: int = component_value(left, lp, le)
        rv: int = component_value(right, rp, re)
        if lv < rv:
            return -1
        if lv > rv:
            return 1
        lp = le + 1
        rp = re + 1
    return 0
''', [(("1","1"),0),(("1","1.0.0"),0),(("0.0","0"),0),(("1.2","1.10"),-1),(("2","1.999"),1),(("1.0.1","1"),1),(("1","1.0.1"),-1),(("999","998.999"),1),(("0.1","0.0.9"),1),(("1.2.3","1.2.3"),0),(("1.2.3","1.2.4"),-1),(("1.0.0.0.0.0.0.0","1"),0)])
task("key_value_parse", "Split ASCII text at the first = into a TextPair(first=key, second=value), trimming only U+0020 spaces from both sides. The input is guaranteed to contain = and its trimmed key is nonempty. Preserve additional equals signs in the value and preserve tabs.", '''
def trim_space(text: str) -> str:
    start: int = 0
    end: int = length(text)
    while start < end and at(text, start) == " ":
        start = start + 1
    while end > start and at(text, end - 1) == " ":
        end = end - 1
    return part(text, start, end)

def solve(text: str) -> Pair:
    pos: int = 0
    while at(text, pos) != "=":
        pos = pos + 1
    return pair(trim_space(part(text, 0, pos)), trim_space(part(text, pos + 1, length(text))))
''', single([("a=b",("a","b")),(" a = b ",("a","b")),("a=",("a","")),("a=  ",("a","")),("a=b=c",("a","b=c")),("a==",("a","=")),("x y=z z",("x y","z z")),("\ta\t=\tb\t",("\ta\t","\tb\t")),("x= a  b ",("x","a  b")),("KEY=value",("KEY","value")),("a= = ",("a","=")),("  k  = v=x ",("k","v=x"))]))
task("csv_record_parse", "Parse a single ASCII CSV record containing no CR/LF. Fields are comma separated. A quoted field begins with double quote, escapes a quote as doubled quotes, and must close immediately before comma/end. Quotes inside unquoted fields are invalid. Return accepted(value) holding the list of decoded field strings (empty record is one empty field), or rejected(malformed).", '''
def quoted_end(text: str, start: int) -> int:
    pos: int = start + 1
    while pos < length(text):
        if at(text, pos) == "\\\"":
            if at(text, pos + 1) == "\\\"":
                pos = pos + 2
            else:
                return pos + 1
        else:
            pos = pos + 1
    return -1

def field_end(text: str, start: int) -> int:
    if at(text, start) == "\\\"":
        return quoted_end(text, start)
    pos: int = start
    while pos < length(text) and at(text, pos) != ",":
        if at(text, pos) == "\\\"":
            return -1
        pos = pos + 1
    return pos

def decoded_field(text: str, start: int, end: int) -> str:
    if at(text, start) != "\\\"":
        return part(text, start, end)
    out: str = ""
    pos: int = start + 1
    while pos < end - 1:
        ch: str = at(text, pos)
        out = out + ch
        if ch == "\\\"":
            pos = pos + 1
        pos = pos + 1
    return out

def solve(text: str) -> Outcome:
    pos: int = 0
    fields: Words = new_words()
    while pos <= length(text):
        end: int = field_end(text, pos)
        if end < 0:
            return rejected("malformed")
        fields = push(fields, decoded_field(text, pos, end))
        if end == length(text):
            return accepted(fields)
        if at(text, end) != ",":
            return rejected("malformed")
        pos = end + 1
    return rejected("malformed")
''', single([("",("accepted",[""])),(",",("accepted",["", ""])),("a,b,c",("accepted",["a", "b", "c"])),('"a,b",c',("accepted",["a,b", "c"])),('""',("accepted",[""])),('"a""b",,',("accepted",['a"b', "", ""])),('"',("rejected","malformed")),('a"b',("rejected","malformed")),('"a" x',("rejected","malformed")),('"a",',("accepted",["a", ""])),('""""',("accepted",['"'])),('"""',("rejected","malformed")),('a,b,,',("accepted",["a", "b", "", ""]))]))
task("rle_encode", "Run-length encode ASCII uppercase letters A..Z as count followed by letter for every maximal run. Always include count 1. Empty input gives empty output. Input length at most 1000.", '''
def solve(text: str) -> str:
    out: str = ""
    pos: int = 0
    while pos < length(text):
        end: int = pos + 1
        while end < length(text) and at(text, end) == at(text, pos):
            end = end + 1
        out = out + render(end - pos) + at(text, pos)
        pos = end
    return out
''', single([("",""),("A","1A"),("AA","2A"),("AB","1A1B"),("AAABB","3A2B"),("ABBA","1A2B1A"),("Z"*12,"12Z"),("ABCABC","1A1B1C1A1B1C"),("AAAABCCCC","4A1B4C"),("AZZA","1A2Z1A"),("A"*1000,"1000A"),("XXYYYZ","2X3Y1Z")]))
task("rle_decode", "Decode zero or more count-letter groups, where count is canonical decimal 1..100 and letter is ASCII A..Z. Total decoded length must be at most 100. Empty input is accepted. Reject malformed for any syntax/count spelling violation (including count 0 or >100); reject range when valid groups exceed total length 100. Process groups left to right.", '''
def repeat_letter(ch: str, count: int) -> str:
    out: str = ""
    pos: int = 0
    while pos < count:
        out = out + ch
        pos = pos + 1
    return out

def solve(text: str) -> Outcome:
    out: str = ""
    pos: int = 0
    while pos < length(text):
        start: int = pos
        while pos < length(text) and digit(at(text, pos)) >= 0:
            pos = pos + 1
        count: int = uint_value(part(text, start, pos), 100)
        if count <= 0 or at(text, start) == "0":
            return rejected("malformed")
        ch: str = at(text, pos)
        if pos == length(text) or not contains("ABCDEFGHIJKLMNOPQRSTUVWXYZ", ch):
            return rejected("malformed")
        if length(out) + count > 100:
            return rejected("range")
        out = out + repeat_letter(ch, count)
        pos = pos + 1
    return accepted(out)
''', single([("",("accepted","")),("1A",("accepted","A")),("3A2B",("accepted","AAABB")),("1A1A",("accepted","AA")),("100Z",("accepted","Z"*100)),("0A",("rejected","malformed")),("01A",("rejected","malformed")),("101A",("rejected","malformed")),("2a",("rejected","malformed")),("A",("rejected","malformed")),("12",("rejected","malformed")),("60A41B",("rejected","range")),("2A0B",("rejected","malformed"))]))
task("path_normalize", "Normalize an absolute ASCII slash-separated path (input always starts with /). Collapse repeated /, ignore . segments, resolve .. by removing the previous segment, and ignore .. above root. No trailing slash except root. Other segment text, including spaces and ..., is literal.", '''
def parent_path(text: str) -> str:
    pos: int = length(text) - 1
    while pos >= 0:
        if at(text, pos) == "/":
            return part(text, 0, pos)
        pos = pos - 1
    return ""

def add_segment(path: str, segment: str) -> str:
    if segment == "" or segment == ".":
        return path
    if segment == "..":
        return parent_path(path)
    return path + "/" + segment

def solve(text: str) -> str:
    path: str = ""
    start: int = 1
    pos: int = 1
    while pos <= length(text):
        if pos == length(text) or at(text, pos) == "/":
            path = add_segment(path, part(text, start, pos))
            start = pos + 1
        pos = pos + 1
    if path == "":
        return "/"
    return path
''', single([("/","/"),("///","/"),("/a/b","/a/b"),("/a//b/","/a/b"),("/./a/.","/a"),("/a/../b","/b"),("/../../a","/a"),("/a/b/../../","/"),("/.../..","/"),("/a/...","/a/..."),("/a/ /b","/a/ /b"),("/a/../a/./b/..","/a")]))
task("extension_split", "Split a single ASCII filename (no slash) into TextPair(first=stem, second=extension) at its final dot, excluding that dot. A dot at position zero alone does not mark an extension. A later final dot does, even with empty extension. Without such dot return entire filename and empty extension.", '''
def solve(text: str) -> Pair:
    dot: int = -1
    pos: int = 1
    while pos < length(text):
        if at(text, pos) == ".":
            dot = pos
        pos = pos + 1
    if dot < 0:
        return pair(text, "")
    return pair(part(text, 0, dot), part(text, dot + 1, length(text)))
''', single([("",("","")),("a",("a","")),("a.txt",("a","txt")),("a.tar.gz",("a.tar","gz")),(".env",(".env","")),(".env.local",(".env","local")),("a.",("a","")),(".",(".","")),("..",(".","")),("...",("..","")),("A.TXT",("A","TXT")),(" a .x",(" a ","x"))]))
task("glob_match", "Return whether a whole ASCII text matches a glob pattern: ? matches exactly one character, * matches zero or more characters, and every other pattern character is literal. No escape syntax. Text and pattern length at most 100.", '''
def solve(text: str, pattern: str) -> bool:
    ti: int = 0
    pi: int = 0
    star: int = -1
    retry: int = 0
    while ti < length(text):
        ch: str = at(pattern, pi)
        if pi < length(pattern) and (ch == "?" or ch == at(text, ti)):
            ti = ti + 1
            pi = pi + 1
        else:
            if ch == "*":
                star = pi
                retry = ti
                pi = pi + 1
            else:
                if star < 0:
                    return False
                retry = retry + 1
                ti = retry
                pi = star + 1
    while at(pattern, pi) == "*":
        pi = pi + 1
    return pi == length(pattern)
''', [(("",""),True),(("","*"),True),(("","?"),False),(("abc","a?c"),True),(("abc","a*c"),True),(("abbbc","a*b*c"),True),(("abc","*d"),False),(("abcd","a*d?"),False),(("abcdef","*?c*f"),True),(("aaaab","a*b"),True),(("abc","**a**?**c**"),True),(("ab","a"),False),(("a.b","a.b"),True),(("ABC","abc"),False)])
task("wrap_words", "Greedily wrap maximal non-space ASCII words into lines of at most width characters, joined by newline. Normalize separators to one space; remove outer spaces. A word longer than width stays intact alone. width is 1..80, input contains printable ASCII only and at most 1000 characters.", '''
def append_word(out: str, word: str, used: int, width: int) -> str:
    if out == "":
        return word
    if used + 1 + length(word) <= width:
        return out + " " + word
    return out + "\\n" + word

def solve(text: str, width: int) -> str:
    clean: str = compact(text)
    out: str = ""
    used: int = 0
    start: int = 0
    pos: int = 0
    while pos <= length(clean):
        if at(clean, pos) == " " or pos == length(clean):
            word: str = part(clean, start, pos)
            out = append_word(out, word, used, width)
            if used == 0 or used + 1 + length(word) > width:
                used = length(word)
            else:
                used = used + 1 + length(word)
            start = pos + 1
        pos = pos + 1
    return out
''', [(("",5),""),(("   ",3),""),(("a b c",3),"a b\nc"),(("a b c",1),"a\nb\nc"),(("longword x",3),"longword\nx"),(("one two three",7),"one two\nthree"),((" one  two ",80),"one two"),(("ab cd ef",5),"ab cd\nef"),(("abc d",3),"abc\nd"),(("a bc",4),"a bc"),(("a bc",3),"a\nbc"),(("x longword y",3),"x\nlongword\ny")])


def type_name(node: ast.expr) -> str:
    assert isinstance(node, ast.Name)
    return node.id

class Emitter:
    def __init__(self, lang: str, funcs: list[ast.FunctionDef]):
        self.lang = lang
        self.funcs = {f.name: f for f in funcs}
        self.vars: dict[str, str] = {}

    def typ(self, name: str) -> str:
        return TYPES[self.lang][name]

    def infer(self, n: ast.expr) -> str:
        if isinstance(n, ast.Constant):
            return "bool" if isinstance(n.value, bool) else "str" if isinstance(n.value, str) else "int"
        if isinstance(n, ast.Name):
            return self.vars[n.id]
        if isinstance(n, (ast.BoolOp, ast.Compare)):
            return "bool"
        if isinstance(n, ast.UnaryOp):
            return "bool" if isinstance(n.op, ast.Not) else "int"
        if isinstance(n, ast.BinOp):
            return self.infer(n.left)
        if isinstance(n, ast.Call):
            assert isinstance(n.func, ast.Name)
            if n.func.id in self.funcs:
                return type_name(self.funcs[n.func.id].returns)
            return {"length":"int", "at":"str", "part":"str", "contains":"bool", "lower":"str", "upper":"str", "render":"str", "accepted":"Outcome", "rejected":"Outcome", "pair":"Pair", "new_words":"Words", "push":"Words"}[n.func.id]
        raise ValueError(ast.dump(n))

    def expr(self, n: ast.expr) -> str:
        lang = self.lang
        if isinstance(n, ast.Constant):
            if isinstance(n.value, bool):
                return str(n.value) if lang == "python" else str(n.value).lower()
            if isinstance(n.value, str):
                if lang == "jett" and any(ch in n.value for ch in ("\b", "\f")):
                    return 'from_ascii_hex("' + n.value.encode("ascii").hex() + '")'
                out = json.dumps(n.value, ensure_ascii=True)
                if lang == "jett":
                    out = out.replace("{", "{{").replace("}", "}}")
                if lang == "rust":
                    out = out.replace("\\b", "\\u{0008}").replace("\\f", "\\u{000c}") + ".to_string()"
                return out
            return str(n.value)
        if isinstance(n, ast.Name):
            return n.id + (".clone()" if lang == "rust" and self.vars.get(n.id) == "str" else "")
        if isinstance(n, ast.BinOp):
            left, right = self.expr(n.left), self.expr(n.right)
            if lang == "rust" and self.infer(n) == "str":
                return f"({left} + &{right})"
            if lang == "jett" and self.infer(n) == "str":
                return f"concat({left}, {right})"
            op = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Mod: "modulo" if lang == "jett" else "%"}[type(n.op)]
            return f"({left} {op} {right})"
        if isinstance(n, ast.BoolOp):
            op = ("and" if isinstance(n.op, ast.And) else "or") if lang in ("python", "jett") else ("&&" if isinstance(n.op, ast.And) else "||")
            return "(" + f" {op} ".join(self.expr(v) for v in n.values) + ")"
        if isinstance(n, ast.UnaryOp):
            op = "not " if isinstance(n.op, ast.Not) and lang in ("python", "jett") else "!" if isinstance(n.op, ast.Not) else "-"
            return "(" + op + self.expr(n.operand) + ")"
        if isinstance(n, ast.Compare):
            assert len(n.ops) == 1
            op = {ast.Eq:"==", ast.NotEq:"!=", ast.Lt:"<", ast.Gt:">", ast.LtE:"<=", ast.GtE:">="}[type(n.ops[0])]
            return f"({self.expr(n.left)} {op} {self.expr(n.comparators[0])})"
        if isinstance(n, ast.Call):
            assert isinstance(n.func, ast.Name)
            name = n.func.id
            args = [self.expr(a) for a in n.args]
            if name in ("accepted", "rejected"):
                if name == "accepted":
                    return {"jett":f"TextOutcome.accepted({args[0]})", "python":f"TextAccepted({args[0]})", "typescript":f'{{kind: "accepted", value: {args[0]}}}', "go":f"TextAccepted{{Value: {args[0]}}}", "rust":f"TextOutcome::Accepted({args[0]})"}[lang]
                err = n.args[0].value
                return {"jett":f"TextOutcome.rejected(TextError.{err})", "python":f"TextRejected(TextError.{err.upper()})", "typescript":f'{{kind: "rejected", error: "{err}"}}', "go":f"TextRejected{{Error: {err.title()}}}", "rust":f"TextOutcome::Rejected(TextError::{err.title()})"}[lang]
            if name == "pair":
                return {"jett":f"TextPair(first: {args[0]}, second: {args[1]})", "python":f"TextPair({args[0]}, {args[1]})", "typescript":f"{{first: {args[0]}, second: {args[1]}}}", "go":f"TextPair{{First: {args[0]}, Second: {args[1]}}}", "rust":f"TextPair {{first: {args[0]}, second: {args[1]}}}"}[lang]
            if lang == "jett" and name == "at":
                name = "char_read"
            return name + "(" + ", ".join(args) + ")"
        raise ValueError(ast.dump(n))

    def block(self, nodes: list[ast.stmt], depth: int) -> str:
        out: list[str] = []
        lang = self.lang
        indent = "    " * depth
        semi = "" if lang in ("python", "jett") else ";"
        for n in nodes:
            if isinstance(n, ast.AnnAssign):
                assert isinstance(n.target, ast.Name)
                name, typ = n.target.id, type_name(n.annotation)
                self.vars[name] = typ
                value = self.expr(n.value)
                declaration = {"jett":f"mutable {self.typ(typ)} {name} = {value}", "python":f"{name}: {self.typ(typ)} = {value}", "typescript":f"let {name}: {self.typ(typ)} = {value}", "go":f"var {name} {self.typ(typ)} = {value}", "rust":f"let mut {name}: {self.typ(typ)} = {value}"}[lang]
                out.append(indent + declaration + semi)
            elif isinstance(n, ast.Assign):
                assert len(n.targets) == 1 and isinstance(n.targets[0], ast.Name)
                out.append(indent + n.targets[0].id + " = " + self.expr(n.value) + semi)
            elif isinstance(n, ast.Return):
                out.append(indent + "return " + self.expr(n.value) + semi)
            elif isinstance(n, (ast.If, ast.While)):
                word = "if" if isinstance(n, ast.If) else ("for" if lang == "go" else "while")
                test = self.expr(n.test)
                if lang == "typescript":
                    test = "(" + test + ")"
                end = ":" if lang in ("python", "jett") else " {"
                out.append(indent + word + " " + test + end)
                out.append(self.block(n.body, depth + 1))
                if lang not in ("python", "jett"):
                    out.append(indent + "}")
                if n.orelse:
                    out.append(indent + "else" + end)
                    out.append(self.block(n.orelse, depth + 1))
                    if lang not in ("python", "jett"):
                        out.append(indent + "}")
            else:
                raise ValueError(ast.dump(n))
        rendered = "\n".join(out)
        if lang == "go":
            rendered = re.sub(r"}\n\s*else", "} else", rendered)
        return rendered

    def function(self, f: ast.FunctionDef, signature: bool = False) -> str:
        self.vars = {a.arg: type_name(a.annotation) for a in f.args.args}
        args = [f"{a.arg}: {self.typ(type_name(a.annotation))}" for a in f.args.args]
        typ = self.typ(type_name(f.returns))
        if self.lang == "jett":
            head = f"function {f.name}({', '.join(args)}) returns {typ}"
        elif self.lang == "python":
            head = f"def {f.name}({', '.join(args)}) -> {typ}"
        elif self.lang == "typescript":
            head = f"export function {f.name}({', '.join(args)}): {typ}"
        elif self.lang == "go":
            args = [f"{a.arg} {self.typ(type_name(a.annotation))}" for a in f.args.args]
            head = f"func {f.name}({', '.join(args)}) {typ}"
        else:
            head = f"pub fn {f.name}({', '.join(args)}) -> {typ}"
        if signature:
            return head
        suffix = ":" if self.lang in ("python", "jett") else " {"
        body = self.block(f.body, 1)
        return head + suffix + "\n" + body + ("\n}" if self.lang not in ("python", "jett") else "")

PRELUDE = {
"jett": '''namespace benchmark
function from_ascii_hex(text: string) returns string:
    bytes encoded = bytes.from_hex(text) handle error:
        return ""
    string decoded = bytes.to_string(view encoded) handle error:
        return ""
    return decoded
function concat(left: string, right: string) returns string:
    return "{left}{right}"
function length(text: string) returns int64:
    return string.length(text)
function char_read(text: string, pos: int64) returns string:
    string ch = string.char_at(text, pos) handle:
        default ""
    return ch
function part(text: string, start: int64, end: int64) returns string:
    return string.slice(text, start, end)
function contains(text: string, needle: string) returns bool:
    return string.contains(text, needle)
function lower(text: string) returns string:
    return string.lower(text)
function upper(text: string) returns string:
    return string.upper(text)
function render(value: int64) returns string:
    return string.from_int64(value)
''',
"python": '''from dataclasses import dataclass
from enum import Enum

def length(text: str) -> int:
    return len(text)
def at(text: str, pos: int) -> str:
    return text[pos] if 0 <= pos < len(text) else ""
def part(text: str, start: int, end: int) -> str:
    return text[start:end]
def contains(text: str, needle: str) -> bool:
    return needle in text
def lower(text: str) -> str:
    return text.lower()
def upper(text: str) -> str:
    return text.upper()
def render(value: int) -> str:
    return str(value)
''',
"typescript": '''function length(text: string): number { return text.length; }
function at(text: string, pos: number): string { return text.charAt(pos); }
function part(text: string, start: number, end: number): string { return text.slice(start, end); }
function contains(text: string, needle: string): boolean { return text.includes(needle); }
function lower(text: string): string { return text.toLowerCase(); }
function upper(text: string): string { return text.toUpperCase(); }
function render(value: number): string { return String(value); }
''',
"go": '''package benchmark
import ("strings"; "strconv")
func length(text string) int64 { return int64(len(text)) }
func at(text string, pos int64) string { if pos < 0 || pos >= int64(len(text)) { return "" }; return text[pos:pos+1] }
func part(text string, start int64, end int64) string { return text[start:end] }
func contains(text string, needle string) bool { return strings.Contains(text, needle) }
func lower(text string) string { return strings.ToLower(text) }
func upper(text string) string { return strings.ToUpper(text) }
func render(value int64) string { return strconv.FormatInt(value, 10) }
''',
"rust": '''fn length(text: String) -> i64 { i64::try_from(text.len()).unwrap_or(0) }
fn at(text: String, pos: i64) -> String { usize::try_from(pos).ok().and_then(|p| text.get(p..p+1)).unwrap_or("").to_string() }
fn part(text: String, start: i64, end: i64) -> String { match (usize::try_from(start), usize::try_from(end)) { (Ok(a), Ok(b)) => text.get(a..b).unwrap_or("").to_string(), _ => String::new() } }
fn contains(text: String, needle: String) -> bool { text.contains(&needle) }
fn lower(text: String) -> String { text.to_ascii_lowercase() }
fn upper(text: String) -> String { text.to_ascii_uppercase() }
fn render(value: i64) -> String { value.to_string() }
''',
}

DECLS = {
"Outcome": {
"jett": "enum TextError:\n    empty\n    malformed\n    range\nenum TextOutcome:\n    accepted(value: string)\n    rejected(error: TextError)\n",
"python": 'class TextError(Enum):\n    EMPTY = "empty"\n    MALFORMED = "malformed"\n    RANGE = "range"\n@dataclass(frozen=True)\nclass TextAccepted:\n    value: str\n@dataclass(frozen=True)\nclass TextRejected:\n    error: TextError\ntype TextOutcome = TextAccepted | TextRejected\n',
"typescript": 'export type TextError = "empty" | "malformed" | "range";\nexport type TextOutcome = { readonly kind: "accepted"; readonly value: string } | { readonly kind: "rejected"; readonly error: TextError };\n',
"go": 'type TextError int\nconst (Empty TextError = iota; Malformed; Range)\ntype TextOutcome interface { isTextOutcome() }\ntype TextAccepted struct { Value string }\ntype TextRejected struct { Error TextError }\nfunc (TextAccepted) isTextOutcome() {}\nfunc (TextRejected) isTextOutcome() {}\n',
"rust": '#[derive(Debug, PartialEq, Eq)]\npub enum TextError { Empty, Malformed, Range }\n#[derive(Debug, PartialEq, Eq)]\npub enum TextOutcome { Accepted(String), Rejected(TextError) }\n',
},
"Pair": {
"jett": "struct TextPair:\n    first: string\n    second: string\n",
"python": "@dataclass(frozen=True)\nclass TextPair:\n    first: str\n    second: str\n",
"typescript": "export type TextPair = { readonly first: string; readonly second: string };\n",
"go": "type TextPair struct { First string; Second string }\n",
"rust": "#[derive(Debug, PartialEq, Eq)]\npub struct TextPair { pub first: String, pub second: String }\n",
}}

LIST_PRELUDE = {
"jett": '''function new_words() returns list[string]:
    return list.new[string]()
function push(values: list[string], value: string) returns list[string]:
    return list.append[string](values, value)
''',
"python": 'def new_words() -> list[str]:\n    return []\ndef push(values: list[str], value: str) -> list[str]:\n    return values + [value]\n',
"typescript": 'function new_words(): string[] { return []; }\nfunction push(values: string[], value: string): string[] { return [...values, value]; }\n',
"go": 'func new_words() []string { return []string{} }\nfunc push(values []string, value string) []string { return append(values, value) }\n',
"rust": 'fn new_words() -> Vec<String> { Vec::new() }\nfn push(mut values: Vec<String>, value: String) -> Vec<String> { values.push(value); values }\n',
}

def payload_kind(item: Task) -> str:
    return "int" if item.name in NUMERIC_TASKS else "Words" if item.name == "csv_record_parse" else "str"

class RemoveRender(ast.NodeTransformer):
    def visit_Call(self, node: ast.Call) -> ast.AST:
        self.generic_visit(node)
        if isinstance(node.func, ast.Name) and node.func.id == "accepted":
            arg = node.args[0]
            if isinstance(arg, ast.Call) and isinstance(arg.func, ast.Name) and arg.func.id == "render":
                node.args[0] = arg.args[0]
        return node

def expected_value(item: Task, expected: object) -> object:
    if item.name in NUMERIC_TASKS and expected[0] == "accepted":
        return ("accepted", int(expected[1]))
    return expected

def needed_functions(source: str) -> list[ast.FunctionDef]:
    all_nodes = ast.parse(HELPERS + source).body
    funcs = {n.name:n for n in all_nodes if isinstance(n, ast.FunctionDef)}
    needed = {"solve"}
    while True:
        new = set(needed)
        for name in needed:
            new.update(n.func.id for n in ast.walk(funcs[name]) if isinstance(n, ast.Call) and isinstance(n.func, ast.Name) and n.func.id in funcs)
        if new == needed:
            return [f for name,f in funcs.items() if name in needed]
        needed = new

def literal(value: object, lang: str) -> str:
    if isinstance(value, list):
        values = ", ".join(literal(v, lang) for v in value)
        return {"python":"[" + values + "]", "typescript":"[" + values + "]", "go":"[]string{" + values + "}", "rust":"vec![" + values + "]", "jett":"list(" + values + ")"}[lang]
    if isinstance(value, str):
        if lang == "jett" and any(ch in value for ch in ("\b", "\f")):
            return 'hidden_ascii("' + value.encode("ascii").hex() + '")'
        out = json.dumps(value)
        if lang == "jett":
            out = out.replace("{", "{{").replace("}", "}}")
        if lang == "rust":
            out = out.replace("\\b", "\\u{0008}").replace("\\f", "\\u{000c}") + ".to_string()"
        return out
    if isinstance(value, bool):
        return str(value) if lang == "python" else str(value).lower()
    return str(value)

def generate() -> None:
    template = json.loads((ROOT / "benchmarks/tasks/score_lines/task.json").read_text())
    for item in TASKS:
        directory = ROOT / "benchmarks/tasks" / ("text_" + item.name)
        directory.mkdir(exist_ok=True)
        funcs = needed_functions(item.source)
        if item.name in NUMERIC_TASKS:
            funcs = [RemoveRender().visit(f) for f in funcs]
        main = next(f for f in funcs if f.name == "solve")
        kind = type_name(main.returns)
        spec = {"id":"text_" + item.name, "version":"1.0.0", "title":item.name.replace("_", " ").capitalize(), "category":"text_parsing" if kind == "Outcome" else "text_transformation", "difficulty":"medium" if kind == "Outcome" or item.name in ("glob_match", "strip_line_comments", "path_normalize", "camel_to_snake", "wrap_words") else "easy", "statement":item.statement, "constraints":["All text is ASCII; unless a narrower task bound is stated, each input string has at most 1000 characters.", "Preserve the exact declared public types and solve signature. Helpers are allowed.", "No input/output, exception throwing, panic, tests, or static diagnostic suppression in the submitted source."], "adapters":{}}
        for lang, ext in LANGS.items():
            emitter = Emitter(lang, funcs)
            declarations = DECLS.get(kind, {}).get(lang, "")
            payload = payload_kind(item)
            if kind == "Outcome" and payload != "str":
                replacements = {"jett":("value: string", "value: " + TYPES[lang][payload]), "python":("value: str", "value: " + TYPES[lang][payload]), "typescript":("readonly value: string", "readonly value: " + TYPES[lang][payload]), "go":("Value string", "Value " + TYPES[lang][payload]), "rust":("Accepted(String)", "Accepted(" + TYPES[lang][payload] + ")")}
                old, new = replacements[lang]
                declarations = declarations.replace(old, new)
            prelude = PRELUDE[lang]
            if payload == "Words":
                prelude += LIST_PRELUDE[lang]
            if lang == "python" and kind not in ("Outcome", "Pair"):
                prelude = prelude.replace("from dataclasses import dataclass\nfrom enum import Enum\n", "")
            if lang == "python" and kind == "Pair":
                prelude = prelude.replace("from enum import Enum\n", "")
            baseline = prelude + "\n" + declarations + "\n" + "\n\n".join(emitter.function(f) for f in funcs) + "\n"
            # Python annotations use actual published type names too.
            baseline = baseline.replace(" -> Outcome:", " -> TextOutcome:").replace(" -> Pair:", " -> TextPair:")
            (directory / f"baseline.{ext}").write_text(baseline, newline="\n")
            signature_prefix = "namespace benchmark\n\n" if lang == "jett" else "package benchmark\n\n" if lang == "go" else "from dataclasses import dataclass\nfrom enum import Enum\n\n" if lang == "python" and kind in ("Outcome", "Pair") else ""
            adapter = copy.deepcopy(template["adapters"][lang])
            adapter["signature"] = signature_prefix + declarations + emitter.function(main, True)
            # Generic source restrictions; exhaustive matching is not required by these signatures.
            adapter["forbidden_patterns"] = [p for p in adapter.get("forbidden_patterns", []) if not ("catch-all" in p["message"] or "default switch" in p["message"] or "wildcard match" in p["message"])]
            if kind == "Outcome" and lang == "jett":
                adapter["forbidden_patterns"].append({"pattern": "(?m)^\\s*(?:other|_)\\s*:", "message":"catch-all match arms are forbidden; handle all declared enum variants explicitly"})
            for p in adapter["forbidden_patterns"]:
                p["message"] = p["message"].replace("return ScoreFailure", "use the declared return type").replace("return Failure", "use the declared return type").replace("return rejected", "use the declared return type")
            spec["adapters"][lang] = adapter
            if lang == "python":
                (directory / "pyrightconfig.json").write_text(json.dumps({"include":["solution.py", "hidden.py"],"pythonVersion":"3.12","typeCheckingMode":"strict"}, indent=2)+"\n", newline="\n")
            hidden = make_hidden(item, lang, kind)
            (directory / adapter["hidden"]).write_text(hidden, newline="\n")
        (directory / "task.json").write_text(json.dumps(spec, indent=2)+"\n", newline="\n")
        fixtures = []
        for args, expected in item.cases:
            expected = expected_value(item, expected)
            outcome = expected
            if kind == "Outcome":
                tag, value = expected
                outcome = {"kind":tag, "value" if tag == "accepted" else "error":value}
            elif kind == "Pair":
                outcome = {"first":expected[0], "second":expected[1]}
            fixtures.append({"inputs":dict(zip([a.arg for a in main.args.args], args)), "expected":outcome})
        (directory / "cases.json").write_text(json.dumps({"task_id":spec["id"], "cases":fixtures}, indent=2)+"\n", newline="\n")
    print(f"Generated {len(TASKS)} tasks, {len(TASKS)*5} adapters, {sum(len(t.cases) for t in TASKS)} cases per language.")
    format_sources()

def format_sources() -> None:
    """Keep regenerated native sources in their standard formatting."""
    jett = ROOT / "target/debug" / ("jett.exe" if __import__("os").name == "nt" else "jett")
    for item in TASKS:
        directory = ROOT / "benchmarks/tasks" / ("text_" + item.name)
        if jett.is_file():
            for filename in ("baseline.jett", "hidden.jett"):
                subprocess.run([str(jett), "format", str(directory / filename)], check=True, capture_output=True, text=True)
        if shutil.which("gofmt"):
            subprocess.run(["gofmt", "-w", str(directory / "baseline.go"), str(directory / "hidden_test.go")], check=True)
        if shutil.which("rustfmt"):
            subprocess.run(["rustfmt", "--edition", "2024", str(directory / "baseline.rs"), str(directory / "hidden.rs")], check=True)

def make_hidden(item: Task, lang: str, kind: str) -> str:
    checks: list[str] = []
    for i, (args, expected) in enumerate(item.cases):
        expected = expected_value(item, expected)
        call = "solve(" + ", ".join(literal(v, lang) for v in args) + ")"
        if kind == "Outcome":
            tag, value = expected
            if lang == "jett":
                call = "hidden_outcome(" + call + ")"
                encoded = str(value)
                if isinstance(value, list):
                    encoded = "".join(str(len(v)) + ":" + v for v in value)
                wanted = literal(tag + ":" + encoded, lang)
            elif lang == "python":
                wanted = f"TextAccepted({literal(value, lang)})" if tag == "accepted" else "TextRejected(TextError." + value.upper() + ")"
            elif lang == "typescript":
                wanted = '{kind: "accepted", value: ' + literal(value, lang) + '}' if tag == "accepted" else '{kind: "rejected", error: ' + literal(value, lang) + '}'
            elif lang == "go":
                wanted = 'TextAccepted{Value: ' + literal(value, lang) + '}' if tag == "accepted" else 'TextRejected{Error: ' + value.title() + '}'
            else:
                wanted = 'TextOutcome::Accepted(' + literal(value, lang) + ')' if tag == "accepted" else 'TextOutcome::Rejected(TextError::' + value.title() + ')'
        elif kind == "Pair":
            a, b = expected
            if lang == "jett":
                call = "hidden_pair(" + call + ")"
                wanted = literal(str(len(a))+":"+a+str(len(b))+":"+b, lang)
            elif lang == "python":
                wanted = f"TextPair({literal(a, lang)}, {literal(b, lang)})"
            elif lang == "typescript":
                wanted = f"{{first: {literal(a, lang)}, second: {literal(b, lang)}}}"
            elif lang == "go":
                wanted = f"TextPair{{First: {literal(a, lang)}, Second: {literal(b, lang)}}}"
            else:
                wanted = f"TextPair {{first: {literal(a, lang)}, second: {literal(b, lang)}}}"
        else:
            wanted = literal(expected, lang)
            if lang == "go" and kind == "int":
                wanted = f"int64({wanted})"
        checks.append({"jett":f"    assert {call} == {wanted}", "python":f"assert {call} == {wanted}, {i}", "typescript":f"check({call}, {wanted}, {i});", "go":f"    if got := {call}; !reflect.DeepEqual(got, {wanted}) {{ t.Fatalf(\"case {i}: got %#v\", got) }}", "rust":f"    assert_eq!({call}, {wanted}, \"case {i}\");"}[lang])
    if lang == "jett":
        head = ""
        if item.name == "escape_json_string":
            head = '''function hidden_ascii(text: string) returns string:
    bytes encoded = bytes.from_hex(text) handle error:
        return ""
    string decoded = bytes.to_string(view encoded) handle error:
        return ""
    return decoded
'''
        if kind == "Outcome":
            head = '''function hidden_error(error: TextError) returns string:
    match error:
        empty:
            return "empty"
        malformed:
            return "malformed"
        range:
            return "range"
function hidden_outcome(outcome: TextOutcome) returns string:
    match outcome:
        accepted(value):
            return "accepted:{value}"
        rejected(error):
            return "rejected:{hidden_error(error)}"
'''
            if payload_kind(item) == "Words":
                head = '''function hidden_words(values: list[string]) returns string:
    mutable string encoded = ""
    for value in values:
        encoded = "{encoded}{string.length(value)}:{value}"
    return encoded
''' + head.replace('return "accepted:{value}"', 'return "accepted:{hidden_words(value)}"')
        if kind == "Pair":
            head = '''function hidden_pair(value: TextPair) returns string:
    return "{string.length(value.first)}:{value.first}{string.length(value.second)}:{value.second}"
'''
        # Verify bodies have bounded statement counts: one block per case.
        return head + "\n".join(f"verify hidden_case_{i}:\n{check}" for i, check in enumerate(checks)) + "\n"
    if lang == "python":
        imports = "solve" + (", TextAccepted, TextRejected, TextError" if kind == "Outcome" else ", TextPair" if kind == "Pair" else "")
        return "from solution import " + imports + "\n\n" + "\n".join(checks) + "\n"
    if lang == "typescript":
        typ = TYPES[lang][kind]
        imports = ", type " + typ if kind in ("Outcome", "Pair") else ""
        compare = "got !== want"
        if kind == "Pair":
            compare = "got.first !== want.first || got.second !== want.second"
        if kind == "Outcome":
            compare = 'got.kind !== want.kind || (got.kind === "accepted" && want.kind === "accepted" && got.value !== want.value) || (got.kind === "rejected" && want.kind === "rejected" && got.error !== want.error)'
            if payload_kind(item) == "Words":
                compare = compare.replace("got.value !== want.value", "(got.value.length !== want.value.length || want.value.some((v, p) => v !== got.value[p]))")
        return 'import { solve' + imports + ' } from "./solution.js";\n' + f"function check(got: {typ}, want: {typ}, index: number): void {{\n" + f'  if ({compare}) throw new Error(`case ${{index}}`);\n}}\n' + "\n".join(checks) + "\n"
    if lang == "go":
        return 'package benchmark\nimport ("testing"; "reflect")\nfunc TestHidden(t *testing.T) {\n' + "\n".join(checks) + "\n}\n"
    return 'include!("solution.rs");\n#[test]\nfn hidden_cases() {\n' + "\n".join(checks) + "\n}\n"

if __name__ == "__main__":
    generate()
